// FIX: Add a Deno types reference to resolve the "Cannot find name 'Deno'" error.
/// <reference types="https://deno.land/x/deno/cli/types/deno.d.ts" />

import { GoogleGenAI, Modality } from "https://aistudiocdn.com/@google/genai@^1.28.0";

// This is a Deno-based Netlify function.
// It will be executed on the server, not in the browser.
export default async (req: Request) => {
  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }

  // API_KEY is securely accessed from Netlify's environment variables
  const apiKey = Deno.env.get('API_KEY');
  if (!apiKey) {
    return new Response(JSON.stringify({ error: "API_KEY not configured on the server." }), { 
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  const ai = new GoogleGenAI({ apiKey });
  
  try {
    const { action, payload } = await req.json();

    switch (action) {
      case 'generateMessage': {
        const { prompt } = payload;
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Act as a loving person writing a time capsule message. Based on the following prompt, write a heartfelt, warm, and encouraging message of about 100-150 words. Do not use markdown. Prompt: "${prompt}"`,
        });
        return new Response(JSON.stringify({ text: response.text }), {
          headers: { 'Content-Type': 'application/json' },
        });
      }

      case 'generateImage': {
        const { message } = payload;
        // First, generate a visual prompt from the message
        const promptGenResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Based on the following heartfelt message, create a short, visually descriptive prompt for an image generation AI. The prompt should capture the core emotion and theme (e.g., 'A serene and nostalgic black and white photograph of a quiet lake at dawn', 'A moody, high-contrast, monochrome digital art piece representing a hopeful future'). Do not include any people in the prompt. Focus on abstract concepts and beautiful scenery. Message: "${message}"`,
        });
        const visualPrompt = promptGenResponse.text;

        // Then, generate the image
        const imageResponse = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: `Black and white photograph, nostalgic, high contrast, fine art. ${visualPrompt}`,
            config: {
              numberOfImages: 1,
              aspectRatio: '1:1',
              outputMimeType: 'image/jpeg',
            },
        });
        
        if (imageResponse.generatedImages && imageResponse.generatedImages.length > 0) {
            const base64ImageBytes = imageResponse.generatedImages[0].image.imageBytes;
            const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
            return new Response(JSON.stringify({ imageUrl }), {
              headers: { 'Content-Type': 'application/json' },
            });
        }
        throw new Error("No image was generated by the API.");
      }

      case 'generateSong': {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-preview-tts",
            contents: [{ parts: [{ text: 'Say cheerfully: Welcome to Timeless!' }] }],
            config: {
                responseModalities: [Modality.AUDIO],
                speechConfig: {
                    voiceConfig: {
                        prebuiltVoiceConfig: { voiceName: 'Kore' },
                    },
                },
            },
        });
        const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
        return new Response(JSON.stringify({ base64Audio }), {
          headers: { 'Content-Type': 'application/json' },
        });
      }

      default:
        return new Response(JSON.stringify({ error: `Unknown action: ${action}` }), { 
          status: 400,
          headers: { 'Content-Type': 'application/json' },
        });
    }

  } catch (error) {
    console.error("Error in Netlify function:", error);
    return new Response(JSON.stringify({ error: error.message || 'An internal server error occurred.' }), { 
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
};